name: CI
on:
- push
jobs:
  xenial:
    container:
      image: vapor/swift:5.1-xenial
    services:
      psql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_USER: steampress
          MYSQL_DB: steampress-test
          MYSQL_PASSWORD: password
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
      env:
        DB_HOSTNAME: mysql
        DB_PORT: 3306
  bionic:
    container:
      image: vapor/swift:5.1-bionic
    services:
      psql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_USER: steampress
          MYSQL_DB: steampress-test
          MYSQL_PASSWORD: password
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Bionic Tests
      run: swift test --enable-test-discovery --sanitize=thread --enable-code-coverage
      env:
        DB_HOSTNAME: mysql
        DB_PORT: 3306
    - name: Setup container for codecov upload
      run: apt-get update && apt-get install curl
    - name: Process coverage file
      run: llvm-cov show .build/x86_64-unknown-linux/debug/SteampressFluentMysqlPackageTests.xctest -instr-profile=.build/x86_64-unknown-linux/debug/codecov/default.profdata > coverage.txt
    - name: Upload code coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_UPLOAD_KEY }}
        file: coverage.txt
